# Generated by Django 2.0.4 on 2018-04-21 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toque',
            fields=[
                ('toque_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('author_username', models.CharField(max_length=300)),
                ('audio', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('surname', models.CharField(max_length=300)),
                ('reg_date', models.DateTimeField(verbose_name='date registered')),
                ('birth_date', models.DateTimeField(verbose_name='birth date')),
                ('last_pub', models.DateTimeField(verbose_name='date last published')),
            ],
        ),
        migrations.AddField(
            model_name='toque',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundFeed.User'),
        ),
    ]
